#!/bin/bash

## Created By Aditya Shakya

rofi -modi run,drun -show drun -theme orange-applauncher -show-icons -theme-str 'window { width: 40%; }' -theme-str 'window { font: "Gohu GohuFont 10"; }' -drun-icon-theme "Papirus"
